### ISSUE TITLE
(String) argument suggestions do not show up because argument succeeds parsing

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#144] opened 2020-11-22 18:16 UTC
I didn't know whether to put this in the PR or as a separate issue, so I'm putting it out here.

**Note: no brigadier is used**

https://github.com/Incendo/cloud/blob/1.2.0-dev/cloud-core/src/main/java/cloud/commandframework/CommandTree.java#L508

In the CommandTree suggestions code, the following is done when providing suggestions for non-static arguments:
```java
            // START: Preprocessing
            final ArgumentParseResult<Boolean> preParseResult = child.getValue().preprocess(
                    commandContext,
                    commandQueue
            );
            if (preParseResult.getFailure().isPresent() || !preParseResult.getParsedValue().orElse(false)) {
                final String value = stringOrEmpty(commandQueue.peek());
                commandContext.setCurrentArgument(child.getValue());
                return child.getValue().getSuggestionsProvider().apply(commandContext, value);
            }
            // END: Preprocessing

            // START: Parsing
            commandContext.setCurrentArgument(child.getValue());
            final ArgumentParseResult<?> result = child.getValue().getParser().parse(commandContext, commandQueue);
            if (result.getParsedValue().isPresent()) {
                commandContext.store(child.getValue().getName(), result.getParsedValue().get());
                return this.getSuggestions(commandContext, commandQueue, child);
            } else if (result.getFailure().isPresent()) {
                final String value = stringOrEmpty(commandQueue.peek());
                commandContext.setCurrentArgument(child.getValue());
                return child.getValue().getSuggestionsProvider().apply(commandContext, value);
            }
```

It is difficult to see the problem, until you start using suggestion providers. The problem is that when you add a StringArgument with a custom suggestion provider, the parsing will succeed even when the value being parsed isn't one of the suggestions. As a result, players can start typing and see the full list, but the moment they type one more character, all suggestions disappear.

I will probably fix this in my PR https://github.com/Incendo/cloud/pull/142 but need to know whether this was intentional behavior.

My proposed fix will be to not call the deeper getSuggestions() function when the number of remaining elements in the command queue is 0, and instead do the (parse) failure case.

The only workaround right now is to not use the suggestion provider, but make a custom argument parser which rejects values that aren't part of the enumeration. That's not a solution for people that want to accept non-suggested input.

**Comment by bergerkiller** [comment] 2020-11-22 18:24
Similar problem when theres command:
`/command <arg> literal`

And suggestions: [hello, helloworld]

You don't want it to hide the fact hello**world** exists as other option once you type:
`/command hello`

But once you type an extra space after hello, then you do want to hide the helloworld bit and show the literal instead.

**Comment by jmanpenilla** [comment] 2020-11-22 21:32
If you have a fix for this, having it in a separate PR would be appreciated. It sounds like you might be running into an issue with the same root cause as this: https://github.com/Incendo/cloud/pull/122

**Comment by bergerkiller** [comment] 2020-11-23 07:43
Currently https://github.com/Incendo/cloud/pull/142 also fixes this issue, but it could be a separate PR if that is preferred.

**Comment by jmanpenilla** [comment] 2020-11-23 07:51
Yeah, that would be preferred

**Comment by bergerkiller** [comment] 2020-11-23 09:36
Is there a way to make one PR a prerequisite for another PR? I'll out it in it's own PR, but need to refer to it from https://github.com/Incendo/cloud/pull/142 otherwise the commit will show up twice, which is weird.

**Comment by Proximyst** [comment] 2020-11-23 10:38
Just rebase onto your other branch; when we merge it, either you rebase this, or we will do it for you if/when this is merged.

**Closed** 2020-12-03 11:04 UTC
