### ISSUE TITLE
Tab completions on greedy strings only work before first space

### ISSUE THREAD

**Issue by YouHaveTrouble** [Incendo/cloud#339] opened 2022-02-12 15:07 UTC
When using suggestions provider for greedy string argument, completion method only fires if the argument input does not contain spaces.
Tested and confirmed on cloud 1.6.1

**Comment by egg82** [comment] 2022-02-12 15:21
Some related info from the Discord:

I've got this argument:
![direct](https://user-images.githubusercontent.com/903688/153717160-95498c0b-97bb-4a05-8f1e-cb28dbe41c2d.png)
With this code:
![direct (1)](https://user-images.githubusercontent.com/903688/153717163-3d12ad26-9c84-42e8-94c1-75decf6d4de3.png)
Which I run like this:
![direct (2)](https://user-images.githubusercontent.com/903688/153717176-23531220-075b-4205-ac30-bbaeb4e5d40d.png)
Which provides this output:
![direct (3)](https://user-images.githubusercontent.com/903688/153717180-70e26933-f9d2-4c04-b44e-44ebd542a496.png)

**Comment by jpenilla** [comment] 2023-01-28 19:18
Duplicate of #190

**Closed by jpenilla** 2023-01-28 19:18 UTC
Labels: bug
